name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PHP App
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /var/www/users.lucasbrum.net/db
            cd /var/www/users.lucasbrum.net
            git clone git@github.com:sistematico/php-mvc-users.git
            git checkout HEAD^ db/database.sqlite
            git pull
            touch /var/www/users.lucasbrum.net/db/database.sqlite